EPOCHS = 10
IMG_WIDTH = 30
IMG_HEIGHT = 30
NUM_CATEGORIES = 43
TEST_SIZE = 0.4

SIGN_NAMES = {
    0:  "Gioi han toc do (20km/h)",
    1:  "Gioi han toc do (30km/h)",
    2:  "Gioi han toc do (50km/h)",
    3:  "Gioi han toc do (60km/h)",
    4:  "Gioi han toc do (70km/h)",
    5:  "Gioi han toc do (80km/h)",
    6:  "Het gioi han toc do (80km/h)",
    7:  "Gioi han toc do (100km/h)",
    8:  "Gioi han toc do (120km/h)",
    9:  "Cam vuot",
    10: "Cam vuot (xe tren 3.5 tan)",
    11: "Uu tien tai nga tu",
    12: "Duong uu tien",
    13: "Nhuong duong",
    14: "Dung lai (Stop)",
    15: "Cam xe co gioi",
    16: "Cam xe tai tren 3.5 tan",
    17: "Cam vao (No entry)",
    18: "Canh bao chung",
    19: "Duong cong nguy hiem (trai)",
    20: "Duong cong nguy hiem (phai)",
    21: "Duong cong doi",
    22: "Duong xau / go ghe",
    23: "Duong tron",
    24: "Duong hep ben phai",
    25: "Cong truong dang thi cong",
    26: "Den tin hieu giao thong",
    27: "Canh bao nguoi di bo",
    28: "Canh bao tre em",
    29: "Canh bao xe dap",
    30: "Canh bao bang / tuyet",
    31: "Canh bao dong vat hoang da",
    32: "Het tat ca gioi han va cam vuot",
    33: "Re phai phia truoc",
    34: "Re trai phia truoc",
    35: "Chi di thang",
    36: "Di thang hoac re phai",
    37: "Di thang hoac re trai",
    38: "Di ve ben phai",
    39: "Di ve ben trai",
    40: "Vong xuyen bat buoc",
    41: "Het cam vuot",
    42: "Het cam vuot (xe tren 3.5 tan)",
}